# Generated by Django 5.2.4 on 2025-07-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('tg_username', models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя пользователя')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя')),
                ('photo', models.ImageField(null=True, upload_to='media/users/', verbose_name='Фотография пользователя')),
                ('registered_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Название')),
                ('photo1', models.ImageField(null=True, upload_to='media/product/', verbose_name='Фотография 1')),
                ('photo2', models.ImageField(null=True, upload_to='media/product/', verbose_name='Фотография 2')),
                ('photo3', models.ImageField(null=True, upload_to='media/product/', verbose_name='Фотография 3')),
                ('photo4', models.ImageField(null=True, upload_to='media/product/', verbose_name='Фотография 4')),
                ('photo5', models.ImageField(null=True, upload_to='media/product/', verbose_name='Фотография 5')),
                ('photo6', models.ImageField(null=True, upload_to='media/product/', verbose_name='Фотография 6')),
                ('photo7', models.ImageField(null=True, upload_to='media/product/', verbose_name='Фотография 7')),
                ('photo8', models.ImageField(null=True, upload_to='media/product/', verbose_name='Фотография 8')),
                ('photo9', models.ImageField(null=True, upload_to='media/product/', verbose_name='Фотография 9')),
                ('photo10', models.ImageField(null=True, upload_to='media/product/', verbose_name='Фотография 10')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.BigIntegerField(default=0, null=True, verbose_name='Цена')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Название')),
                ('photo', models.ImageField(null=True, upload_to='media/orders/', verbose_name='Фотография')),
                ('price', models.BigIntegerField(default=0, null=True, verbose_name='Цена')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='api.product')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
