# Generated by Django 5.2.4 on 2025-07-27 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.users'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name='Фотография 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo10',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name='Фотография 10'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name='Фотография 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name='Фотография 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name='Фотография 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name='Фотография 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo6',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name='Фотография 6'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo7',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name='Фотография 7'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo8',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name='Фотография 8'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo9',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/', verbose_name='Фотография 9'),
        ),
    ]
