# Generated by Django 5.2.4 on 2025-07-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_orders_user_alter_product_photo1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tg_username',
        ),
    ]
