# Generated by Django 5.2.4 on 2025-10-14 14:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_users_name_remove_users_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to='poster', verbose_name='Постер')),
            ],
            options={
                'verbose_name': 'Постер',
                'verbose_name_plural': 'Постер',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Промокод')),
                ('discount', models.BigIntegerField(default=0, null=True, verbose_name='Процент скидки в %')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='isreturn',
            field=models.BooleanField(default=False, verbose_name='Возврат'),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('ASSEMBLING', 'Собирается '), ('ONTHEWAY', 'В пути'), ('ATTHEPOINT', 'На пункте выдачи'), ('DELIVERED', 'Доставлено')], max_length=350, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='orders',
            name='time',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 10, 14, 14, 10, 36, 472915, tzinfo=datetime.timezone.utc), verbose_name='Дата оформления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='track_code',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Трек номер'),
        ),
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
        migrations.AddField(
            model_name='product',
            name='flug_new',
            field=models.BooleanField(default=False, verbose_name='Флаг Новинки'),
        ),
        migrations.AddField(
            model_name='product',
            name='flug_popular',
            field=models.BooleanField(default=False, verbose_name='Флаг популярно'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Количество на складе'),
        ),
        migrations.AddField(
            model_name='product',
            name='oldprice',
            field=models.BigIntegerField(default=0, null=True, verbose_name='Прошлая цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='users',
            name='notification_liked',
            field=models.BooleanField(default=True, verbose_name='Уведомление о новинках избранных'),
        ),
        migrations.AddField(
            model_name='users',
            name='notification_order_status',
            field=models.BooleanField(default=True, verbose_name='Уведомление о статусе заказа '),
        ),
        migrations.AddField(
            model_name='users',
            name='notification_promotion',
            field=models.BooleanField(default=True, verbose_name='Уведомление об Акциях и Новинках'),
        ),
        migrations.AddField(
            model_name='users',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='photo',
            field=models.ImageField(null=True, upload_to='orders', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.product'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.users'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo1',
            field=models.ImageField(null=True, upload_to='product', verbose_name='Фотография 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo10',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Фотография 10'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Фотография 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Фотография 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Фотография 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Фотография 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo6',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Фотография 6'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo7',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Фотография 7'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo8',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Фотография 8'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo9',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Фотография 9'),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now_add=True, verbose_name='Дата и время')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='api.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='api.users')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True, verbose_name='Имя')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст отзыва')),
                ('stars', models.BigIntegerField(default=5, null=True, verbose_name='Количество звезд')),
                ('time', models.DateField(auto_now_add=True, verbose_name='Дата и время')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.users')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='UsedPromocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_promocodes', to='api.promocode')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_promocodes', to='api.users')),
            ],
            options={
                'verbose_name': 'Использованный промокод',
                'verbose_name_plural': 'Использованные промокоды',
            },
        ),
    ]
