# Generated by Django 5.2.4 on 2025-10-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_poster_promocode_orders_isreturn_orders_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='time',
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата оформления'),
        ),
    ]
