# Generated by Django 5.2.4 on 2025-10-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_orders_time_alter_orders_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moysklad_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='ID в МойСклад'),
        ),
    ]
