# Generated by Django 5.2.4 on 2025-10-24 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_moysklad_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoySkladWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moysklad_id', models.CharField(max_length=255, unique=True, verbose_name='ID склада в МойСклад')),
                ('name', models.CharField(max_length=255, verbose_name='Название склада')),
                ('meta_href', models.URLField(max_length=500, verbose_name='Ссылка на склад в API')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Склад МойСклад',
                'verbose_name_plural': 'Склады МойСклад',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='last_sync_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней синхронизации'),
        ),
        migrations.AddField(
            model_name='product',
            name='moysklad_synced',
            field=models.BooleanField(default=False, verbose_name='Синхронизирован с МойСклад'),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Склад для оприходования товара в МойСклад', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.moyskladwarehouse', verbose_name='Склад'),
        ),
    ]
