# Generated by Django 5.2.4 on 2025-10-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_moyskladwarehouse_product_last_sync_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='auto_sync',
            field=models.BooleanField(default=True, help_text='Автоматически синхронизировать товар с МойСклад при сохранении', verbose_name='Автоматическая синхронизация'),
        ),
        migrations.AddField(
            model_name='product',
            name='sync_error',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Ошибка синхронизации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_sync_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата последней синхронизации'),
        ),
        migrations.AlterField(
            model_name='product',
            name='moysklad_synced',
            field=models.BooleanField(default=False, editable=False, verbose_name='Синхронизирован с МойСклад'),
        ),
    ]
