# Generated by Django 5.2.4 on 2025-11-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_product_options_product_auto_sync_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
    ]
