# Generated by Django 5.2.4 on 2025-11-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_orders_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cdek_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер накладной CDEK'),
        ),
        migrations.AddField(
            model_name='orders',
            name='cdek_uuid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CDEK UUID'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Город доставки'),
        ),
        migrations.AddField(
            model_name='orders',
            name='pvz_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код ПВЗ'),
        ),
        migrations.AddField(
            model_name='orders',
            name='pvz_work_time',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='График работы ПВЗ'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='orders', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='product',
            name='oldprice',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Прошлая цена'),
        ),
    ]
