# Generated by Django 5.2.4 on 2025-11-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_orderitem_orders_products_review_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время оформления'),
        ),
    ]
