# Generated by Django 5.2.4 on 2025-12-13 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_users_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='cdek_number',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='cdek_uuid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='delivery_city',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='pvz_code',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='pvz_work_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='auto_sync',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_sync_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moysklad_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moysklad_synced',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sync_error',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('ASSEMBLING', 'Собирается '), ('ONTHEWAY', 'В пути'), ('DELIVERED', 'Доставлено')], max_length=350, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category'),
        ),
        migrations.DeleteModel(
            name='MoySkladWarehouse',
        ),
    ]
