# Generated by Django 5.2.4 on 2026-02-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_product_warehouse_remove_orders_cdek_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveSmallIntegerField(default=10, verbose_name='Процент сервисного сбора')),
            ],
            options={
                'verbose_name': 'Сервисный сбор',
                'verbose_name_plural': 'Сервисный сбор',
            },
        ),
    ]
