# Generated by Django 5.2.4 on 2026-02-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_servicefeesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_step',
            field=models.PositiveIntegerField(default=1, verbose_name='Шаг количества'),
        ),
    ]
