# Generated by Django 5.2.4 on 2026-02-11 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_product_quantity_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('PAID', 'Оплачен'), ('ASSEMBLING', 'Собирается '), ('ONTHEWAY', 'В пути'), ('DELIVERED', 'Доставлено')], max_length=350, null=True, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('SUCCEEDED', 'Оплачен'), ('CANCELED', 'Отменен'), ('WAITING', 'Ожидает подтверждения')], default='PENDING', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('address', models.TextField(blank=True)),
                ('is_pickup', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('promocode', models.CharField(blank=True, max_length=100)),
                ('goods', models.JSONField(default=list)),
                ('summary', models.JSONField(default=dict)),
                ('confirmation_url', models.TextField(blank=True)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_sessions', to='api.orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to='api.users')),
            ],
            options={
                'verbose_name': 'Платежная сессия',
                'verbose_name_plural': 'Платежные сессии',
            },
        ),
    ]
