# Generated by Django 5.2.4 on 2026-02-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_orders_status_paymentsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_pickup',
            field=models.BooleanField(default=False, verbose_name='Самовывоз'),
        ),
    ]
