# Generated by Django 5.2.4 on 2026-02-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_orders_is_pickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_days_ahead', models.PositiveSmallIntegerField(default=0, verbose_name='Минимум дней до доставки')),
                ('max_days_ahead', models.PositiveSmallIntegerField(default=14, verbose_name='Максимум дней до доставки')),
            ],
            options={
                'verbose_name': 'Настройки отложенной доставки',
                'verbose_name_plural': 'Настройки отложенной доставки',
            },
        ),
        migrations.CreateModel(
            name='DeliveryTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32, unique=True, verbose_name='Слот времени')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Слот времени доставки',
                'verbose_name_plural': 'Слоты времени доставки',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_time_slot',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Временной слот доставки'),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='delivery_time_slot',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
