# Generated by Django 5.2.4 on 2026-02-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_deliverysettings_deliverytimeslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_recipient_self',
            field=models.BooleanField(default=True, verbose_name='Заказчик является получателем'),
        ),
        migrations.AddField(
            model_name='orders',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя получателя'),
        ),
        migrations.AddField(
            model_name='orders',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=64, verbose_name='Телефон получателя'),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='assemblers_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='is_recipient_self',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
