# Generated by Django 5.2.4 on 2026-02-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_orders_is_recipient_self_orders_recipient_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(default='Напоминаем: заказ #{order_number} ожидает оплату. Сумма: {amount} ₽.\nОплатить: {payment_url}', verbose_name='Текст напоминания')),
                ('delay_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='Отправить через X минут')),
            ],
            options={
                'verbose_name': 'Напоминание об оплате',
                'verbose_name_plural': 'Напоминание об оплате',
            },
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='reminder_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentsession',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
