# Generated by Django 5.2.4 on 2026-03-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_paymentremindersettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='staff_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Чат персонала'),
        ),
        migrations.AddField(
            model_name='orders',
            name='staff_message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Сообщение персонала'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('PLACED', 'Оформление'), ('ASSEMBLING_STARTED', 'Сборка начата'), ('ASSEMBLING_DONE', 'Сборка готова'), ('COURIER_PICKED', 'Курьер забрал'), ('DELIVERING', 'Доставка'), ('READY_FOR_PICKUP', 'Готов к выдаче'), ('ISSUED', 'Выдан'), ('PAID', 'Оплачен'), ('ASSEMBLING', 'Собирается '), ('ONTHEWAY', 'В пути'), ('DELIVERED', 'Доставлено')], max_length=350, null=True, verbose_name='Статус'),
        ),
    ]
