# Generated by Django 5.2.4 on 2026-03-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_orders_staff_chat_id_orders_staff_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='orders',
            name='payer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя заказчика'),
        ),
        migrations.AddField(
            model_name='orders',
            name='payer_phone',
            field=models.CharField(blank=True, max_length=64, verbose_name='Телефон заказчика'),
        ),
        migrations.AddField(
            model_name='orders',
            name='promocode',
            field=models.CharField(blank=True, max_length=100, verbose_name='Промокод'),
        ),
    ]
