# Dockerfile.frontend
FROM node:20-alpine AS build

WORKDIR /app
COPY frontend/ /app/
RUN npm install && npm run build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
